// What the screen shows when the boss walks past.
export const bossLines = [
  '$ npm run build',
  '',
  '> platform-services@4.12.0 build',
  '> tsc -p tsconfig.build.json && node scripts/bundle.mjs',
  '',
  'Compiling 1,284 files...',
  '  src/core/scheduler/queue.ts',
  '  src/core/scheduler/worker-pool.ts',
  '  src/core/scheduler/retry-policy.ts',
  '  src/adapters/postgres/connection.ts',
  '  src/adapters/postgres/migrations/0042_add_index.ts',
  '  src/adapters/redis/cache.ts',
  '  src/api/routes/accounts.ts',
  '  src/api/routes/billing.ts',
  '  src/api/routes/reports.ts',
  '  src/api/middleware/auth.ts',
  '  src/api/middleware/rate-limit.ts',
  '  src/domain/invoice/invoice.ts',
  '  src/domain/invoice/line-item.ts',
  '  src/domain/ledger/reconcile.ts',
  'Type-check complete in 41.8s',
  '',
  'Bundling with esbuild...',
  '  dist/server.js        2.4mb',
  '  dist/worker.js        1.1mb',
  '  dist/cli.js         312.6kb',
  'Bundle complete in 3.2s',
  '',
  '$ npm test -- --coverage',
  '',
  ' PASS  src/core/scheduler/queue.spec.ts (4.113 s)',
  ' PASS  src/core/scheduler/retry-policy.spec.ts',
  ' PASS  src/adapters/postgres/connection.spec.ts (6.207 s)',
  ' PASS  src/adapters/redis/cache.spec.ts',
  ' PASS  src/api/routes/accounts.spec.ts (8.941 s)',
  ' PASS  src/api/routes/billing.spec.ts (11.382 s)',
  ' PASS  src/api/middleware/auth.spec.ts',
  ' PASS  src/domain/invoice/invoice.spec.ts',
  ' PASS  src/domain/ledger/reconcile.spec.ts (14.590 s)',
  '',
  'Test Suites: 9 passed, 9 total',
  'Tests:       312 passed, 312 total',
  'Snapshots:   18 passed, 18 total',
  'Time:        52.44 s',
  '',
  '----------------------|---------|----------|---------|---------|',
  'File                  | % Stmts | % Branch | % Funcs | % Lines |',
  '----------------------|---------|----------|---------|---------|',
  'All files             |   91.42 |    84.17 |   93.05 |   91.88 |',
  ' core/scheduler       |   95.10 |    88.62 |   97.14 |   95.33 |',
  ' adapters/postgres    |   88.73 |    79.40 |   90.00 |   89.12 |',
  ' api/routes           |   90.26 |    82.95 |   92.31 |   90.71 |',
  ' domain/ledger        |   93.84 |    87.50 |   95.00 |   94.02 |',
  '----------------------|---------|----------|---------|---------|',
  '',
  '$ npm run lint',
  '',
  '> eslint . --max-warnings 0',
  '',
  '$ ',
];
